# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.20241001.1
_src_path: gh:level12/copier-py-package
author_email: randy@syrings.us
author_name: Randy Syring
project_name: Flac
py_module: flac
python_version: '3.12'
script_name: flac
use_pipx: false
virtualenv_name: flac
