version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@5.2

jobs:

  nox:

    docker:
      - image: ghcr.io/level12/ubuntu-mive:24-3.12

    steps:
      - checkout

      - run:
          name: Debugging info
          command: |
              ls -al
              echo $PATH

      - run:
          name: OS Prep
          command: |
              mise trust
              mise install

      - run:
          name: run nox
          command: |
            mise exec -- uv run --only-group nox nox

      - store_test_results:
          path: ci/test-reports/

      - codecov/upload


workflows:
  main:
    jobs:
      - nox
