version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@4.1.0

jobs:

  nox:

    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Debugging info
          command: |
              ls -al
              echo $PATH

      - run:
          name: Install OS tools
          command: |
              python -m pip install -r requirements/ci.txt
              python --version
              python -m nox --version

      - run:
          name: run nox
          command: |
            python -m nox

      - store_test_results:
          path: ci/test-reports/

      - codecov/upload


workflows:
  main:
    jobs:
      - nox
