version: 2.1
jobs:
  build:
    docker:
      - image: level12/python-test-multi
      - image: postgres:12-alpine
        environment:
            # Ok for CI, potentially UNSAFE in other applications.  Don't blindly copy & paste
            # without considering implications.
            POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout

      - run:
          name: folder listing for debugging
          command: ls -al

      - run:
          name: install latest version of tox
          command: >
              python3.8 -m pip install --upgrade --force-reinstall --quiet tox
      - run:
          name: version checks
          command: |
              python3.8 --version
              tox --version
      - run:
          name: run tox
          command: tox

      - store_test_results:
          path: .ci/test-reports/

      - run:
          name: push code coverage
          command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t 6795ab8d-d0ba-4a64-812c-9649f6e6058f
