#!/usr/bin/env python3
import pathlib

import click

from flac.contrib.shiv import build


@click.command()
@click.option('--skip-deps', is_flag=True, default=False,
              help='Delete everything and start over.')
def shiv_build(skip_deps):
    build(
        pathlib.Path(__file__).parent,
        '{{ cookiecutter.project_namespace }}',
        'python3.7',
        skip_deps,
        '{{ cookiecutter.project_namespace }}-py37',
    )
    msg = 'Built python3.7 version'
    if not skip_deps:
        msg += ' with all deps (use --skip-deps next time if they haven\'t' \
            ' changed for a faster build)'
    print(msg)


if __name__ == '__main__':
    shiv_build()
